### ISSUE TITLE
 itemscroller-crafting-fix in 1.18.2 crash the game

### ISSUE THREAD

**Issue by Pietr06** [Andrews54757/itemscroller-crafting-fix#13]
starting with just  itemscroller-crafting-fix and the latest verion of malilib (0.12.0) the game crash
![image](https://user-images.githubusercontent.com/88508843/158068974-e4a33de3-c5fc-4933-b34e-27873452add1.png)
[latest.log](https://github.com/Andrews54757/itemscroller-crafting-fix/files/8240132/latest.log)

**Comment by Andrews54757** [comment]
Fixed
