### ISSUE TITLE
Client framedrop drastically drops and sometimes freezes when mass crafting on servers using the autocrafting table carpet extension

### ISSUE THREAD

**Issue by naliuj** [Andrews54757/itemscroller-crafting-fix#15]
Like the title says. Specifically,  using [this](https://github.com/gnembon/carpet-autoCraftingTable) extension or the autocrafting table rule in QuickCarpet. I never had issues with it in 1.17 but I have had this issue ever since the first 1.18 version. There doesn't seem to be any lag from Masa's normal itemscroller version.

**Comment by Nyx-9841** [comment]
I had the exact same issue. The ping and mspt are fine, but the frame rates just drop to zero. This doesn't seem to take effect on singleplayer, but if you try to mass craft on multiplayer, you will experience a lot of lag, even with small loads like a simple shulker box of items.

**Comment by Andrews54757** [comment]
It is a mod conflict. This sounds like an issue with the autocrafting implementation. Craftfix doesn't do any additional modifications to vanilla code that is not in the original. Please let them know.
