### ISSUE TITLE
Disregard nbt/durability differences for specific items when mass-dropping items

### ISSUE THREAD

**Issue by U5B** [Andrews54757/itemscroller-crafting-fix#16]
Original issues: https://github.com/maruohon/itemscroller/issues/49

I believe a list of items to ignore will be the easiest way to implement.
Other more complicated methods could involve a global option to ignore either durability or nbt data.

The server I play on has a grinder that drops stone_swords with differing durability, and an option to ignore durability would be nice.

**Comment by Andrews54757** [comment]
It's on Masa's TODO list
