### ISSUE TITLE
is/will there be a version for 1.19? 

### ISSUE THREAD

**Issue by RainVYT** [Andrews54757/itemscroller-crafting-fix#18]
question is stated in the title :D

**Comment by mrGRINCH** [comment]
Would also love a 1.19 update.

**Comment by SadPeace** [comment]
if you guys are still looking.
https://github.com/Andrews54757/itemscroller-crafting-fix/releases/tag/1.2.6.119-dirty

**Comment by ItsYusei99** [comment]
https://github.com/Andrews54757/itemscroller-crafting-fix/pull/21

**Comment by Andrews54757** [comment]
https://github.com/Andrews54757/itemscroller-crafting-fix/releases

**Comment by FreezeHorizon** [comment]
1.19 version for malilib 0.13.0?
