### ISSUE TITLE
Please Update to 1.19.4

### ISSUE THREAD

**Issue by Bobisawesome07** [Andrews54757/itemscroller-crafting-fix#31]
I don't know how difficult updating mods can be, but an eta for the 1.19.4 version would be appreciated because this mod is a life saver.

**Comment by Andrews54757** [comment]
It's not difficult, it takes 5 min. I'm just lazy. Will think about doing this soontm

**Comment by Colorflow-exe** [comment]
> 不难，5分钟。我只是懒惰。很快就会考虑这样做

It's that OK?

**Comment by Bobisawesome07** [comment]
Stop being lazy and update please

**Comment by Yekerrrrr** [comment]
Please update the mod 
crafting is very laggy.

**Comment by voidrinix** [comment]
#33

**Comment by Heitzenberg** [comment]
> #33

Working fine, thank you!

**Comment by voidrinix** [comment]
btw if you don't want to compile the mod by yourself, you can download a compiled version from the releases in my fork, because the author doesn't post the release in this repo.
https://github.com/RinixGG/itemscroller-crafting-fix/releases/tag/1.2.7.1194

**Comment by Colorflow-exe** [comment]
> 顺便说一句，如果你不想自己编译 mod，你可以从我的 fork 中的版本下载编译版本，因为作者没有在这个 repo 中发布版本。 https://github.com/RinixGG/itemscroller-crafting-fix/releases/tag/1.2.7.1194
thx!
