### ISSUE TITLE
Not an Issue, but please update the mod to 1.20.2

### ISSUE THREAD

**Issue by ghost** [Andrews54757/itemscroller-crafting-fix#41]
For getting more diamonds I switched to 1.20.2, now I am having problem to craft all diamods to diamond block without Itemscroller Andrews version

Humble request, you will get tons of blessings from me and my family

**Comment by Bobisawesome07** [comment]
Please update

**Comment by Vaskyy** [comment]
we need mass crafting pleaaaaase
