### ISSUE TITLE
Please update to 1.20.4

### ISSUE THREAD

**Issue by Crystal0404** [Andrews54757/itemscroller-crafting-fix#45]
It's so user-friendly.

**Comment by ZeterTheDuck** [comment]
Yes, please. I didn't realize how good this mod is until I can't use it

**Comment by WRTY1** [comment]
I hope this can help you. It's build for fabric 0.15.7 and malilib 0.18.1 for 1.20.4. I get source code by this [fork](https://github.com/shebpamm/itemscroller-crafting-fix/tree/fabric_1.20.x). But I can upload file so I fork the shebpamm's source code then this is the file [itemscroller-1.20.4-craftfix](https://github.com/WRTY1/itemscroller-crafting-fix/releases/download/v1.0.0/itemscroller-fabric-1.20.4-craftfix-0.21.0.jar)
